### ISSUE TITLE
Truncate first_name and last_name

### ISSUE THREAD

**Issue by pdpinch** [mitocw/django-cas-provider#8]
first_name and last_name are limited to 30 characters in the database and when we get a value longer than 30 characters from Touchstone, the app crashes. 

Since names aren't displayed in edX, the quickest solution is to truncate names over 30 characters. 

Maybe in some future version we can use django 2.0 which include support for and migration to longer last names.

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you start working on this first thing tomorrow?

**Comment by amir-qayyum-khan** [comment]
sure

**Comment by amir-qayyum-khan** [comment]
@pdpinch i made PR https://github.mit.edu/mitx-devops/mitx-cas

**Comment by pdpinch** [comment]
closed via 4220b7b
